server:
    port: 8000
spring:
    cloud:
        config:
          enabled: false
        discovery:
            enabled: false
        gateway:
            routes:
                - id: r1
                  uri: http://localhost:8001
                  predicates:
                    - Path=/api/v1/customers/**
                - id: r2
                  uri: http://localhost:8002
                  predicates:
                    - Path=/api/v1/accounts/**
                      
    application:
        name: gateway-service
    