spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: proxidev
        password: proxidev
        url: jdbc:postgresql://localhost:5432/spring_account_ms
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernete:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    cloud:
        config:
            enabled: false
            discovery:
                enabled: false


server:
    port: 8002
    